# Generated by Django 6.1 on 2026-09-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPI', '0004_alter_comment_created_at_alter_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='blogAPI.category'),
        ),
    ]
